---
coverage:
  precision: 2
  round: down
  range: "85...100"
  status:
    project:
      default:
        target: 85%
        threshold: 15%
        paths:
          - "include/**"
          - "src/**"
    patch:
      default:
        informational: true
        target: 75%
        threshold: 100%

comment:
  layout: "condensed_header, tree, condensed_footer"
  show_critical_paths: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
